version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: front-docker
    ports:
      - "80:3000"
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - mynetwork

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: back-docker
    ports:
      - "5001:5001"
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: "mongo"
    container_name: db-docker
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - mynetwork

  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    container_name: jenkins
    restart: always
    user: root
    ports:
      - "8080:8080"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
    networks:
      - mynetwork

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    networks:
      - mynetwork
    volumes:
      - data:/data
      - jenkins-data:/opt/jenkins/data

volumes:
  data:
  jenkins-data:

networks:
  mynetwork:
    name: "mynetwork"
